name: Send Daily Scrape (20:00 AZT)

on:
  # Manual işə salma imkanı verir
  workflow_dispatch:
  # Cron cədvəli
  schedule:
    # Hər gün 20:00 AZT (16:00 UTC) üçün:
    - cron: '0 16 * * *' 

jobs:
  run_scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Send Scrape Request to Render
        # Sənin Render URL-ə GET sorğusu göndərilir
        run: |
          echo "Sending Scrape Request to Render..."
          # DÜZƏLİŞ: Scraper artıq daha uzun müddət işlədiyi üçün vaxt 180 saniyəyə qaldırıldı!
          curl --max-time 180 https://yeni-projem-1.onrender.com/api/scrape
